### ISSUE TITLE
Dev Container link in the Read Me goes to a place holder page.

### ISSUE THREAD

**Issue by ntabernacle** [Azure-Samples/rag-postgres-openai-python#36]
### Description

When you click the Dev Container link in the https://github.com/Azure-Samples/rag-postgres-openai-python?tab=readme-ov-file#vs-code-dev-containers section it takes you to a place holder page: https://github.com/Azure-Samples/rag-postgres-openai-python/blob/main/placeholder

### Environment

N/A

**Comment by pamelafox** [comment]
Thanks, fixed!
