### ISSUE TITLE
Remove unused code from container

### ISSUE THREAD

**Issue by john0isaac** [Azure-Samples/rag-postgres-openai-python#52]
### Description

Currently, we are zipping the whole src folder and uploading it to the container.
The code in the `frontend/` folder is not needed after we compile the `static` folder.

https://github.com/Azure-Samples/rag-postgres-openai-python/blob/b05f38ab45698331561b3c252e2a2c5c7da7bae9/azure.yaml#L7

### Proposal

**[Option 1]** Move the `frontend` folder outside of the `src` folder

**[Option 2]** Restructure `src` folder to this:

```md
src
│
└─── frontend
│    .....
└─── backend
    │    .dockerignore
    │    Dockerfile
    │    .....
    └─── fastapi_app
         │    .....
         └─── static
```

Then use backend folder in `azure.yaml`

**Comment by pamelafox** [comment]
Ah right, that looks like what we do for https://github.com/Azure-Samples/azure-search-openai-demo/tree/main/app, probably a good idea.

**Comment by john0isaac** [comment]
Yeah, option 2 is based of the ai-search sample. will do a pr for it then
