### ISSUE TITLE
Prepackage hooks runs after building the docker image

### ISSUE THREAD

**Issue by john0isaac** [Azure-Samples/rag-postgres-openai-python#53]
### Description

The first deployment fails (obviously as the static folder was not included in the docker image)

![image](https://github.com/Azure-Samples/rag-postgres-openai-python/assets/64026625/1f82f0fa-ccc5-4390-b9fc-794a42f20bd8)

After deploying again the website works (as the static folder is already there from the first deployment)

### Proposal

Is this an `azd` failure or do we understand the service lifecycle wrong?
The frontend build step is in the prepackage stage yet it happens after building the docker image.

- Move this issue to `azd`? Done
- Add instructions for manually building the frontend before running azd?

**Comment by john0isaac** [comment]
So Wallace Breza says that this should be a prebuild hook not prepackage but let's see what he will say on the issue.
Changing the step from prepackage to prebuild should resolve this issue.
https://github.com/Azure/azure-dev/issues/3546#issuecomment-2005003062

**Comment by pamelafox** [comment]
Huh, thanks for raising that with them. Let's change to prebuild then.

**Comment by john0isaac** [comment]
FYI this needs to be done for all of the samples that has a "build" stage in their lifecycle where it builds a docker image.
Any sample with ACA that has `prepackage` command that runs frontend build needs to be changed to `prebuild`
