### ISSUE TITLE
Run `azd package` fails in Dev Containers

### ISSUE THREAD

**Issue by NanaXiong00** [Azure-Samples/rag-postgres-openai-python#71]
**Describe the issue:**
When executing `azd up` according to [README.md](https://github.com/azure-samples/rag-postgres-openai-python?tab=readme-ov-file#deployment), the error is as follows:
![image](https://github.com/user-attachments/assets/132681ed-20b0-4690-bf41-c907b06672c7)
![image](https://github.com/user-attachments/assets/e5ace623-d879-4f5f-a7c5-cc7cbf324a2b)

**Repro Steps:**
1. Open in Dev Containers.
2. Run `azd auth login` 
3. Run `azd up`

**Environment:**
- Azd version: azd version 1.9.5 (commit cd2b7af9995d358aab33c782614f801ac1997dde)
- OS: Dev Containers

**Expected behavior:**
Run `azd up` can successfully.

@jongio and @pamelafox for notification.

**Comment by pamelafox** [comment]
I sometimes see that when my Docker is having networking issues. Is it constant?

**Comment by NanaXiong00** [comment]
Yes, the above problem is constant.

**Comment by pamelafox** [comment]
Hm, can you try restarting Docker? That's the top suggestion here:
https://stackoverflow.com/questions/61567404/docker-temporary-failure-resolving-deb-debian-org
I just ran azd up in a dev container on my Mac M1, and wasn't able to replicate the connectivity issue.

**Comment by NanaXiong00** [comment]
> Hm, can you try restarting Docker? That's the top suggestion here: https://stackoverflow.com/questions/61567404/docker-temporary-failure-resolving-deb-debian-org I just ran azd up in a dev container on my Mac M1, and wasn't able to replicate the connectivity issue.

I tried restarting Docker, but the above issue still persists in the dev container on Windows and Mac.

**Comment by jongio** [comment]
@NanaXiong00 can you please try again?

**Comment by NanaXiong00** [comment]
> @NanaXiong00 can you please try again?

The latest test results show that the above problems still exist.

**Comment by jongio** [comment]
I was unable to repro this on DevContainers/Windows.  I suggest we say this is an environment/network issue on your end since we can't repro it here.
