### ISSUE TITLE
Run `azd up` fails in Windows

### ISSUE THREAD

**Issue by NanaXiong00** [Azure-Samples/rag-postgres-openai-python#72]
**Describe the issue:**
When executing `azd up` according to [README.md](https://github.com/azure-samples/rag-postgres-openai-python?tab=readme-ov-file#deployment), the error is as follows:
![image](https://github.com/user-attachments/assets/882fb8a6-aba3-4b64-8bb4-3156709f1454)

**Repro Steps:**
1. Download the project code: `azd init -t rag-postgres-openai-python`
2. Install required Python packages: `pip install -r requirements-dev.txt`
3. Run `azd auth login` 
4. Run `azd up`

**Environment:**
- Azd version: azd version 1.9.5 (commit cd2b7af9995d358aab33c782614f801ac1997dde)
- OS: Windows desktop

**Expected behavior:**
Run `azd up` can successfully.

@jongio and @pamelafox for notification.

**Comment by pamelafox** [comment]
Thanks, the instructions were missing an installation step:

https://github.com/Azure-Samples/rag-postgres-openai-python/blob/main/README.md#local-environment

I've changed step 4 to:

pip install -r requirements-dev.txt
pip install -e src/backend

Can you try that?

**Comment by NanaXiong00** [comment]
Follow the above reply steps to test, and the following error message is still displayed:
![image](https://github.com/user-attachments/assets/a86d04b6-4eef-40ce-8572-eb811ce57b81)
![image](https://github.com/user-attachments/assets/68880c1e-df82-405c-86dc-21ddd797e83a)

**Comment by pamelafox** [comment]
I've merged another fix that changes the powershell scripts to use `azd env get-value`. That requires the latest azd version, so I've also added requiredVersions to the azure.yaml to remind folks to upgrade. I've tested the new pwsh scripts on my Mac, but not on a Windows itself. Can you see if it's working for you now?

**Comment by NanaXiong00** [comment]
> I've merged another fix that changes the powershell scripts to use `azd env get-value`. That requires the latest azd version, so I've also added requiredVersions to the azure.yaml to remind folks to upgrade. I've tested the new pwsh scripts on my Mac, but not on a Windows itself. Can you see if it's working for you now?

Based on the latest code tested in Windows environment, the above problems have been fixed.

**Comment by pamelafox** [comment]
Great!
