### ISSUE TITLE
Fail to load web page after `azd up`

### ISSUE THREAD

**Issue by NanaXiong00** [Azure-Samples/rag-postgres-openai-python#73]
**Describe the issue:**
After `azd up`, opening the deployed web page shows failure, the error is as follows:
![image](https://github.com/user-attachments/assets/1cd6930a-bd45-47da-a9f2-63d2cf31e129)
![image](https://github.com/user-attachments/assets/aeab3715-4420-4b5b-b001-584cc47e9559)

**Repro Steps:**
1. Open in GitHub Codespaces.
2. Run `azd auth login` 
3. Run `azd up`
4. Open the deployed web page.

**Environment:**
- Azd version: azd version 1.9.5 (commit cd2b7af9995d358aab33c782614f801ac1997dde)
- OS: Codespaces

**Expected behavior:**
The web pag can load normally.

@jongio and @pamelafox for notification.

**Comment by pamelafox** [comment]
Does it still display the stream timeout if you wait 10 minutes? Are there any errors in the logs?

**Comment by NanaXiong00** [comment]
Based on the latest code test, the above issue can no longer be reproduced.

**Comment by pamelafox** [comment]
Thanks, closing! We did get a fix a few days ago that may have been the culprit.
