### ISSUE TITLE
Any Free Version of this

### ISSUE THREAD

**Issue by Raghucharan16** [Azure-Samples/rag-postgres-openai-python#79]
### Description

What is wrong or what would you like to see improved?
Nothing is Wrong but can we locally set it up with another open source LLM? and also with out cloud costs? just like a standalone application?

**Comment by pamelafox** [comment]
Yes, you can open it in a GitHub Codespace or VS Code Dev Container, which will use Postgres, and then you can configure it to use Ollama, per guide at:
https://github.com/Azure-Samples/rag-postgres-openai-python?tab=readme-ov-file#setting-up-the-environment-file

Let me know if that doesn't work for you.

**Comment by Raghucharan16** [comment]
Sure will check it out. 👍

**Comment by Raghucharan16** [comment]
> Yes, you can open it in a GitHub Codespace or VS Code Dev Container, which will use Postgres, and then you can configure it to use Ollama, per guide at: https://github.com/Azure-Samples/rag-postgres-openai-python?tab=readme-ov-file#setting-up-the-environment-file

> Let me know if that doesn't work for you.

Hi, @pamelafox , can we connect to our own [custom] postgres SQL database? so that LLM should refer that database for any user input questions[ basically to automate customer support service].
