### ISSUE TITLE
Azure Database for PostgreSQL flexible server deployment error

### ISSUE THREAD

**Issue by jkayser225** [Azure-Samples/rag-postgres-openai-python#90]
### Description

I am getting a failure when deploying related to Azure Database for PostgreSQL flexible server.

### Environment

The same exact error happens when utilizing Codespaces, Dev Container, and a local environment.  Where do I update the server name to fix this or is there another reason this is happening.  See error details below: 

You can view detailed progress in the Azure Portal:
  
  (✓) Done: Resource group: Pleasework1-rg (283ms)
  (x) Failed: Azure Database for PostgreSQL flexible server: Pleasework1-pdoenzsorqyks-postgresql (404ms)
  (✓) Done: Log Analytics workspace: Pleasework1-pdoenzsorqyks-loganalytics (16.032s)
  (✓) Done: Azure OpenAI: Pleasework1-pdoenzsorqyks-openai (21.365s)
  (✓) Done: Azure AI Services Model Deployment: Pleasework1-pdoenzsorqyks-openai/gpt-35-turbo (21.904s)
  (✓) Done: Azure AI Services Model Deployment: Pleasework1-pdoenzsorqyks-openai/text-embedding-ada-002 (22.385s)
  (✓) Done: Application Insights: Pleasework1-pdoenzsorqyks-appinsights (884ms)
  (✓) Done: Portal dashboard: Pleasework1-pdoenzsorqyks-appinsights-dashboard (353ms)
  (✓) Done: Container Registry: Pleasework1pdoenzsorqyksregistry (22.938s)
  (✓) Done: Container Apps Environment: Pleasework1-pdoenzsorqyks-containerapps-env (36.137s)
  |    ===| Creating/Updating resources
ERROR: error executing step command 'provision': deployment failed: error deploying infrastructure: deploying to subscription:

Deployment Error Details:
InvalidParameterValue: Invalid value given for parameter serverName. Specify a valid parameter value.

TraceID: 6adc7b8812dd1257360068833ab10a12

**Comment by jkayser225** [comment]
My bad.  I used a capital letter when creating my azure env name.  This issue is resolved.

**Comment by pamelafox** [comment]
Ah, I can fix the Bicep so that it always uses a lowercase version of the env name. Thanks for letting me know!
